/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.cinema.Init;

import com.jdf.swing.helper.JFrameHelper;
import com.senac.cinema.swing.jiFrameFilme;
import com.senac.cinema.swing.jiFrameSala;
import com.senac.cinema.swing.jiFrameSecao;
import com.senac.cinema.swing.jiFrameVenda;

/**
 *
 * @author igors
 */
public class jFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form jFrameMain
     */
    public jFrameMain() {
        initComponents();
        
        // centraliza janela
        setLocationRelativeTo(null);
        
        JFrameHelper fh = new JFrameHelper(this);
        fh.setBiggerSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMain = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuVenda = new javax.swing.JMenu();
        menuVendaItemIngresso = new javax.swing.JMenuItem();
        menuFilme = new javax.swing.JMenu();
        menuFilmeItemManutencao = new javax.swing.JMenuItem();
        menuSala = new javax.swing.JMenu();
        menuSalaItemManutencao = new javax.swing.JMenuItem();
        menuSecao = new javax.swing.JMenu();
        menuSecaoItemManutencao = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjudaItemSobre = new javax.swing.JMenuItem();
        menuAjudaItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopMainLayout = new javax.swing.GroupLayout(desktopMain);
        desktopMain.setLayout(desktopMainLayout);
        desktopMainLayout.setHorizontalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        desktopMainLayout.setVerticalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        menuVenda.setText("Venda");

        menuVendaItemIngresso.setText("Ingressos");
        menuVendaItemIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaItemIngressoActionPerformed(evt);
            }
        });
        menuVenda.add(menuVendaItemIngresso);

        menuPrincipal.add(menuVenda);

        menuFilme.setText("Filme");

        menuFilmeItemManutencao.setText("Manutenção");
        menuFilmeItemManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFilmeItemManutencaoActionPerformed(evt);
            }
        });
        menuFilme.add(menuFilmeItemManutencao);

        menuPrincipal.add(menuFilme);

        menuSala.setText("Sala");

        menuSalaItemManutencao.setText("Manutenção");
        menuSalaItemManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalaItemManutencaoActionPerformed(evt);
            }
        });
        menuSala.add(menuSalaItemManutencao);

        menuPrincipal.add(menuSala);

        menuSecao.setText("Seção");

        menuSecaoItemManutencao.setText("Manutenção");
        menuSecaoItemManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecaoItemManutencaoActionPerformed(evt);
            }
        });
        menuSecao.add(menuSecaoItemManutencao);

        menuPrincipal.add(menuSecao);

        menuAjuda.setText("Ajuda");

        menuAjudaItemSobre.setText("Sobre");
        menuAjuda.add(menuAjudaItemSobre);

        menuAjudaItemSair.setText("Sair");
        menuAjudaItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaItemSairActionPerformed(evt);
            }
        });
        menuAjuda.add(menuAjudaItemSair);

        menuPrincipal.add(menuAjuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAjudaItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuAjudaItemSairActionPerformed

    private void menuFilmeItemManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFilmeItemManutencaoActionPerformed
        jiFrameFilme ff = new jiFrameFilme();
        desktopMain.add(ff);
        ff.setVisible(true);        
    }//GEN-LAST:event_menuFilmeItemManutencaoActionPerformed

    private void menuSalaItemManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalaItemManutencaoActionPerformed
        jiFrameSala fs = new jiFrameSala();
        desktopMain.add(fs);
        fs.setVisible(true);
    }//GEN-LAST:event_menuSalaItemManutencaoActionPerformed

    private void menuSecaoItemManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecaoItemManutencaoActionPerformed
        jiFrameSecao fs = new jiFrameSecao();
        desktopMain.add(fs);
        fs.setVisible(true);
    }//GEN-LAST:event_menuSecaoItemManutencaoActionPerformed

    private void menuVendaItemIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaItemIngressoActionPerformed
        jiFrameVenda fs = new jiFrameVenda();
        desktopMain.add(fs);
        fs.setVisible(true);
    }//GEN-LAST:event_menuVendaItemIngressoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAjudaItemSair;
    private javax.swing.JMenuItem menuAjudaItemSobre;
    private javax.swing.JMenu menuFilme;
    private javax.swing.JMenuItem menuFilmeItemManutencao;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuSala;
    private javax.swing.JMenuItem menuSalaItemManutencao;
    private javax.swing.JMenu menuSecao;
    private javax.swing.JMenuItem menuSecaoItemManutencao;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JMenuItem menuVendaItemIngresso;
    // End of variables declaration//GEN-END:variables
}
