package com.senac.cinema.swing;

import com.jdf.swing.helper.jtable.JTableHelper;
import com.senac.cinema.Controller.FilmeController;
import com.senac.cinema.Domain.Filme;
import com.senac.cinema.Domain.Genero;
import java.util.List;
import javax.swing.JOptionPane;

public class jiFrameFilme extends javax.swing.JInternalFrame {

    private final FilmeController controller;
    private final JTableHelper<Filme> tableHelper;

    public jiFrameFilme() {
        initComponents();

        this.controller = new FilmeController();
        tableHelper = new JTableHelper<>(tbFilmes);

        this.pesquisarFilmes(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneFilmes = new javax.swing.JScrollPane();
        tbFilmes = new javax.swing.JTable();
        btnSalvar = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JToggleButton();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox();
        lblSinopse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopse = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manutenção de Filmes");

        tbFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFilmesMouseClicked(evt);
            }
        });
        scrollPaneFilmes.setViewportView(tbFilmes);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Perquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        lblCodigo.setText("Código");

        txtCodigo.setEditable(false);

        lblNome.setText("Nome");

        lblGenero.setText("Genero");

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Selecione)", "Acao", "Aventura", "Comedia", "Drama", "Ficcao", "Romance", "Suspense", "Terror" }));

        lblSinopse.setText("Sinopse");

        txtSinopse.setColumns(20);
        txtSinopse.setRows(5);
        jScrollPane1.setViewportView(txtSinopse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSinopse)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodigo)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGenero)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(24, 24, 24)
                                .addComponent(txtNome)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSinopse)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(scrollPaneFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(btnPesquisar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        this.pesquisarFilmesPorNome();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        this.pesquisarFilmesPorNome();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void tbFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFilmesMouseClicked
        txtCodigo.setText(String.format("%s", tableHelper.getSelectedObject().getId()));
        txtNome.setText(tableHelper.getSelectedObject().getNome());
        /*
        String generoString;
        generoString = "(Selecione)";
        
        switch(tableHelper.getSelectedObject().getGenero()){
              case Acao:
                generoString = "Acao";
            case Aventura:
                generoString = "Aventura";
            case Comedia:
                generoString = "Comedia";
            case Drama:
                generoString = "Drama";
            case Ficcao:
                generoString = "Ficcao";
            case Romance:
                generoString = "Romance";
            case Suspense:
                generoString = "Suspense";
            case Terror:
                generoString = "Terror";
            default:
                throw new IllegalArgumentException("Gênero não encontrado!");
        }*/
        
        cbGenero.setSelectedItem(tableHelper.getSelectedObject().getGenero());
        txtSinopse.setText(tableHelper.getSelectedObject().getSinopse());
    }//GEN-LAST:event_tbFilmesMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtCodigo.setText(null);
        txtNome.setText(null);
        cbGenero.setSelectedItem("Selecione");
        txtSinopse.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String codigo = txtCodigo.getText();
        Filme filme = new Filme();

        if (codigo != null && !codigo.isEmpty()) {
            filme.setId(Integer.parseInt(codigo));
        }

        String generoString = cbGenero.getSelectedItem().toString();
        Genero genero;

        if ("Acao".equals(generoString)) {
            genero = Genero.Acao;
        } else if ("Aventura".equals(generoString)) {
            genero = Genero.Aventura;
        } else if ("Comedia".equals(generoString)) {
            genero = Genero.Comedia;
        } else if ("Drama".equals(generoString)) {
            genero = Genero.Drama;
        } else if ("Ficcao".equals(generoString)) {
            genero = Genero.Ficcao;
        } else if ("Romance".equals(generoString)) {
            genero = Genero.Romance;
        } else if ("Suspense".equals(generoString)) {
            genero = Genero.Suspense;
        } else {
            genero = Genero.Terror;
        }

        filme.setGenero(genero);
        filme.setNome(txtNome.getText());
        filme.setSinopse(txtSinopse.getText());

        if (filme.getId() > 0) {
            controller.atualizar(filme);
        } else {
            controller.adicionar(filme);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void pesquisarFilmesPorNome() {
        String nome = txtPesquisa.getText();
        this.pesquisarFilmes(nome);
    }

    private void pesquisarFilmes(String nome) {
        try {
            List<Filme> filmeList = null;

            if (nome != null && !nome.isEmpty()) {
                filmeList = this.controller.obterPorNome(nome);
            } else {
                filmeList = this.controller.obterTodos();
            }

            tableHelper.setModel(filmeList);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JComboBox cbGenero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSinopse;
    private javax.swing.JScrollPane scrollPaneFilmes;
    private javax.swing.JTable tbFilmes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextArea txtSinopse;
    // End of variables declaration//GEN-END:variables
}
